### ISSUE TITLE
Babbage Era - New Utxo fields inlineDatum, referenceScriptHash in Utxo (For Koios Backend)

### ISSUE THREAD

**Issue by satran004** [bloxbean/cardano-client-lib#131] opened 2022-07-10 12:39 UTC
There are two new fields added to utxo in Babbage era to support inline datum and script reference. The Utxo class has already been updated with two new fields

```
private String inlineDatum;
private String referenceScriptHash;
``` 

Update Koios backend module to include these new fields in the response.

**Note:** please refer to Blockfrost backend impl change

**Comment by satran004** [comment] 2022-07-10 12:40
fyi @edridudi

**Comment by edridudi** [comment] 2022-08-08 12:35
Duplicate of #148

**Closed by edridudi** 2022-08-08 12:35 UTC
Labels: vasil
